services:
    aroundhub_db:
        image: mariadb:10.6 # mariadb 10.6 버전 이미지 사용
        container_name: db_master
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: aroundhub12#
            MARIADB_DATABASE: springboot
            MARIADB_USER: flature
            MARIADB_PASSWORD: aroundhub12#
        volumes:
            - ./master_db/data:/var/lib/mysql # 각종 log와 index 등이 volume에 저장되는 디렉토리
            - ./master_db/config/:/etc/mysql/conf.d # 이전에 나왔던 ./master/config/my.cnf 를 써줌으로써 설정을 reference 해 줍니다.
        ports:
            - "3308:3306"
    
    aroundhub_redis:
        image: redis:7.0.0
        restart: always
        ports:
            - "6380:6379"
            
    security_pjt:
        image: dydydade/security-pjt:1.0.0
        restart: always
        depends_on:
            - aroundhub_db
            - aroundhub_redis
        ports:
            - "8080:8080"